name: rise_unplugged
version: 1.0.0+1
description: A sleep wellness companion with smart alarms and unplug timer experiences.
publish_to: 'none'
environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  hooks_riverpod: ^3.0.3
  shared_preferences: ^2.2.2
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.4.2
  fl_chart: ^1.1.1
  collection: ^1.18.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  rxdart: ^0.28.0
  url_launcher: ^6.2.5
  package_info_plus: ^9.0.0
  animations: ^2.0.8
  google_fonts: ^6.1.0
  flex_color_scheme: ^8.3.0
  in_app_review: ^2.0.8
  device_info_plus: ^12.1.0
  share_plus: ^7.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^3.2.3
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/ringtones/
    - assets/images/
    - assets/animations/
